### ISSUE TITLE
Incompatible with vite-node and SSR 

### ISSUE THREAD

**Issue by steveblue** [fi3ework/vite-plugin-web-components-hmr#7]
It appears Node requires a polyfill for window.customElements to use this plugin with vite-node and server-side rendering. My main use case for custom elements is server-side rendering with DSD because it's fairly easy.

```
/__web-dev-server__/wc-hmr/runtime.js:5
const originalDefine = window.customElements.define;
                       ^

ReferenceError: window is not defined
    at /__web-dev-server__/wc-hmr/runtime.js:5:24
    at ViteNodeRunner.runModule (file:///Users/steve/www/readymade/node_modules/vite-node/dist/client.mjs:399:11)
 ```

This is the pertenant config:

```
import { hmrPlugin } from 'vite-plugin-web-components-hmr';

export default {
  plugins: [
    hmrPlugin({
      include: ['./src/**/*.ts'],
    }),
  ],
  ```

**Comment by steveblue** [comment]
Seems like #5 is tracking this. It's probably a lot to ask for HMR to work with SSR templates.

**Comment by steveblue** [comment]
Closing.
